services:
  version: "3"
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 5000:80
  
  mysql_db:
    version: "3"
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taravel_docker
    ports:
      - 3306:3306
  
  phpmyadmin:
    version: "3"
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1