version: "3"
services:
  laravel-docker1:
    container_name: laravel-docker1
    build: ./
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 5000:80

  mysql_db:
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taravel_docker
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
